post_install() {
	echo -e "\e[1;33m" # yellow

	echo 'To use ESP-IDF:'
	echo
	echo '   Run `source espsetup` to add idf.py and idf_tools.py'
	echo '   to your current PATH. You will have to do this in every terminal'
	echo '   where you want to use ESP-IDF. Alternatively, you can add'
	echo '   "source espsetup" to ~/.bashrc or the equivalent for'
	echo '   your shell to load ESP-IDF automatically in all terminals.'

	echo -e "\e[1;0m" # default
}

post_upgrade() {
	post_install
}
