# Machine-local Hyprland settings. This file is created only when missing;
# chezmoi does not overwrite it afterwards.
#
# Examples:
# monitor=,preferred,auto,auto,mirror,HDMI-A-1
# env = HYPRCURSOR_SIZE,24
# env = HYPRCURSOR_THEME,rose-pine-hyprcursor
# env = LIBVA_DRIVER_NAME,nvidia
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
