context.objects = [
    {   factory = adapter
        args = {
            factory.name     = support.null-audio-sink
            node.name        = "proaudio_sink"
            node.description = "Pro Audio Devices"
            media.class      = Audio/Sink
            audio.position   = [ AUX0 AUX1 AUX2 AUX3 ]
            monitor.channel-volumes = false
            monitor.passthrough = true
            priority.session = 1000
        }
    }
]
